common:
  room:
    expireTime: 599
  s3:
    bucket: jcopy-storage
develop:
  redis:
    host: 192.168.0.200
    port: 6379
  mongodb:
    user: test
    pwd: test
    host: 192.168.0.200
    port: 27017
    dbName: test
  grpc:
    proto:
      path: '../proto/jcopy.proto'
    RoomService:
      host: localhost
      port: 15000
    StorageService:
      host: localhost
      port: 15001

deploy:
  kafka:
    brokers:
      - 172.31.41.194:9092
    groupid:
      gateway: jcopy-gateway
      room: jcopy-room
      storage: jcopy-storage
  redis:
    host: redis-service
    port: 6379
  mongodb:
    user: test
    pwd: test
    host: mongo-service
    port: 27017
    dbName: test
  grpc:
    proto:
      path: './jcopy.proto'
    RoomService:
      host: room-service
      port: 15000
    StorageService:
      host: storage-service
      port: 15001