develop:
  kafka:
    brokers:
      - localhost:9092
    groupid:
      gateway: jcopy-gateway
      room: ''
      storage: jcopy-storage
  redis:
    host: localhost
    port: 6379
  mongodb:
    user: test
    pwd: test
    host: localhost
    port: 27017
    dbName: test
  grpc: 
    proto:
      path: '../proto/jcopy.proto'
    RoomService:
      host: localhost
      port: 5000
    StorageService:
      host: localhost
      port: 5001
deploy:
  kafka:
    brokers:
      - 172.31.36.85:9092
    groupid:
      gateway: jcopy-gateway
      room: ''
      storage: jcopy-storage    
  redis:
    host: redis-service
    port: 6379
  mongodb:
    user: test
    pwd: test
    host: mongo-service
    port: 27017
    dbName: test
  grpc: 
    proto:
      path: './jcopy.proto'
    RoomService:
      host: room-service
      port: 5000
    StorageService:
      host: storage-service
      port: 5001