name: ALL Container Deploy Hub

on:
  push:
    branches:
      - J165-9-CICD-AWS-Deploy
jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: config file create
        run : |
          echo "{\"accessKeyId\":\"${{secrets.AWS_S3_ACCESS_KEY}}\",\"secretAccessKey\":\"${{secrets.AWS_S3_SECRET_ACCESS_KEY}}\",\"region\":\"ap-northeast-2\"}" > ./gateway/s3.json

      - name: react build setup
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: viewer/package-lock.json

      - name: npm install
        working-directory: ./viewer
        run: npm install

      - name: npm run build
        working-directory: ./viewer
        run: npm run build

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: gateway Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./gateway/Dockerfile
          tags: jhkimdocker/jcopy-gateway:${{secrets.VERSION}}
          push: true

      - name: room test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./room/Dockerfile
          tags: jhkimdocker/jcopy-room:${{secrets.VERSION}}
          push: true

      - name: storage Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./storage/Dockerfile
          tags: jhkimdocker/jcopy-storage:${{secrets.VERSION}}
          push: true

      - name: make zip
        run: |
          zip -r ./test.zip ./test
        shell: bash

      - name: configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

          aws-region: ap-northeast-2

      - name: upload s3
        run: aws s3 cp --region ap-northeast-2 ./test.zip s3://${{secrets.AWS_BUCKET_NAME}}/test1/test.zip

      - name: code deploy
        run: aws deploy create-deployment --application-name ${{secrets.DEPLOY_APPLICATION_NAME}} --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ${{secrets.DEPLOY_GROUP_NAME}} --s3-location bucket=${{secrets.AWS_BUCKET_NAME}},bundleType=zip,key=test1/test.zip
