name: ALL Container Deploy Hub

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: gateway Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/gateway/Dockerfile
          tags: jhkimdocker/jcopy-gateway:v0.0.10
          push: true

      - name: room test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/room/Dockerfile
          tags: jhkimdocker/jcopy-room:v0.0.10
          push: true

      - name: storage Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/storage/Dockerfile
          tags: jhkimdocker/jcopy-storage:v0.0.10
          push: true
