name: ALL Container Deploy Hub

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: config file create
        run : |
          echo "{\"accessKeyId\":\"${{secrets.AWS_S3_ACCESS_KEY}}\",\"secretAccessKey\":\"${{secrets.AWS_S3_SECRET_ACCESS_KEY}}\",\"region\":\"ap-northeast-2\"}" > ./service/gateway/s3.json

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: gateway Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./service/gateway/Dockerfile
          tags: jhkimdocker/jcopy-gateway:v0.1.7
          push: true

      - name: room test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./service/room/Dockerfile
          tags: jhkimdocker/jcopy-room:v0.1.7
          push: true

      - name: storage Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./service/storage/Dockerfile
          tags: jhkimdocker/jcopy-storage:v0.1.7
          push: true